import type { ClipCategory } from '@/lib/domain/categories';
import type { PriorityTier } from '@/lib/domain/thresholds';
import type {
  ClipDimensionScores,
  ScoredClip,
  ScoringEngineName,
  VideoLicense,
} from '@/lib/domain/types';
import { fromJson, getDb, nowIso, toJson, transaction } from '../client';

export type ClipStatus = 'new' | 'approved' | 'rejected' | 'published';

export type RenderStatus = 'none' | 'rendering' | 'done' | 'error';

export type PublishStatus = 'none' | 'publishing' | 'published' | 'error';

/** A clip joined with the episode context the UI always needs alongside it. */
export interface ClipRecord {
  id: number;
  videoId: string;
  runId: number | null;
  segmentIndex: number;
  title: string;
  startSec: number;
  endSec: number;
  durationSec: number;
  finalScore: number;
  confidence: number;
  tier: PriorityTier;
  category: ClipCategory;
  dimensions: ClipDimensionScores;
  whyThisWorks: string[];
  suggestedHook: string;
  suggestedCaption: string;
  editingNotes: string;
  transcript: string;
  engine: ScoringEngineName;
  status: ClipStatus;
  /** Hybrid render integration state. */
  renderStatus: RenderStatus;
  renderJobId: string | null;
  renderPath: string | null;
  renderError: string | null;
  /** Phase 2: SEO metadata generated by the LLM. */
  seoTitle: string | null;
  seoDescription: string | null;
  seoTags: string[];
  seoGeneratedAt: string | null;
  /** Phase 3: publish integration state. */
  publishStatus: PublishStatus;
  publishUrl: string | null;
  publishError: string | null;
  publishDate: string | null;
  createdAt: string;
  episodeTitle: string;
  channelTitle: string;
  channelId: string;
  publishedAt: string;
  /**
   * Reuse rights inherited from the episode. Surfaced on the clip because that
   * is where the publish decision is actually made.
   */
  license: VideoLicense;
  /** Phase 1 (Correctness): highlight debug report (brief §52). */
  endingType: string;
  endingConfidence: number | null;
  nextTopicRemoved: boolean;
  nextTopicStartSec: number | null;
  nextTopicContamination: number | null;
  /** Phase 1 (Master Task Brief §12-14): boundary workflow + debug report. */
  boundaryStatus: string;
  boundaryConfidence: number | null;
  startComplete: boolean;
  repairReason: string | null;
  roughStartSec: number | null;
  roughEndSec: number | null;
  mainTopic: string | null;
  topicBefore: string | null;
  topicAfter: string | null;
  /** Phase 1 (brief §14): ending completeness persisted from the boundary
   * quality report. */
  endingComplete: boolean | null;
  /** Phase 3 (§24-25): publish gates + rights workflow. */
  rightsStatus: string;
  rightsNotes: string | null;
  qcStatus: string;
  qcScore: number | null;
  qcReport: string | null;
  scheduledAt: string | null;
  targetMarket: string | null;
  idempotencyKey: string | null;
}

interface ClipRow {
  id: number;
  video_id: string;
  run_id: number | null;
  segment_index: number;
  title: string;
  start_sec: number;
  end_sec: number;
  duration_sec: number;
  final_score: number;
  confidence: number;
  tier: string;
  category: string;
  dimensions: string;
  why_this_works: string;
  suggested_hook: string;
  suggested_caption: string;
  editing_notes: string;
  transcript: string;
  engine: string;
  status: string;
  render_status: string;
  render_job_id: string | null;
  render_path: string | null;
  render_error: string | null;
  seo_title: string | null;
  seo_description: string | null;
  seo_tags: string | null;
  seo_generated_at: string | null;
  publish_status: string | null;
  publish_url: string | null;
  publish_error: string | null;
  created_at: string;
  episode_title: string | null;
  channel_title: string | null;
  channel_id: string | null;
  published_at: string | null;
  license: string | null;
  ending_type: string | null;
  ending_confidence: number | null;
  next_topic_removed: number | null;
  next_topic_start_sec: number | null;
  next_topic_contamination: number | null;
  boundary_status: string | null;
  boundary_confidence: number | null;
  start_complete: number | null;
  ending_complete: number | null;
  repair_reason: string | null;
  rough_start_sec: number | null;
  rough_end_sec: number | null;
  main_topic: string | null;
  topic_before: string | null;
  topic_after: string | null;
  rights_status: string | null;
  rights_notes: string | null;
  qc_status: string | null;
  qc_score: number | null;
  qc_report: string | null;
  scheduled_at: string | null;
  target_market: string | null;
  idempotency_key: string | null;
}

const EMPTY_DIMENSIONS: ClipDimensionScores = {
  hook: 0,
  curiosity: 0,
  emotion: 0,
  storytelling: 0,
  standalone: 0,
  shareability: 0,
  clarity: 0,
  controversy: 0,
  teachingValue: 0,
  entertainment: 0,
};

function mapClip(row: ClipRow): ClipRecord {
  return {
    id: row.id,
    videoId: row.video_id,
    runId: row.run_id,
    segmentIndex: row.segment_index,
    title: row.title,
    startSec: row.start_sec,
    endSec: row.end_sec,
    durationSec: row.duration_sec,
    finalScore: row.final_score,
    confidence: row.confidence,
    tier: row.tier as PriorityTier,
    category: row.category as ClipCategory,
    dimensions: fromJson<ClipDimensionScores>(row.dimensions, EMPTY_DIMENSIONS),
    whyThisWorks: fromJson<string[]>(row.why_this_works, []),
    suggestedHook: row.suggested_hook,
    suggestedCaption: row.suggested_caption,
    editingNotes: row.editing_notes,
    transcript: row.transcript,
    engine: row.engine as ScoringEngineName,
    status: row.status as ClipStatus,
    renderStatus: (row.render_status ?? 'none') as RenderStatus,
    renderJobId: row.render_job_id ?? null,
    renderPath: row.render_path ?? null,
    renderError: row.render_error ?? null,
    seoTitle: row.seo_title ?? null,
    seoDescription: row.seo_description ?? null,
    seoTags: fromJson<string[]>(row.seo_tags ?? '[]', []),
    seoGeneratedAt: row.seo_generated_at ?? null,
    publishStatus: (row.publish_status ?? 'none') as PublishStatus,
    publishUrl: row.publish_url ?? null,
    publishError: row.publish_error ?? null,
    publishDate: row.published_at ?? null,
    createdAt: row.created_at,
    episodeTitle: row.episode_title ?? '(unknown episode)',
    channelTitle: row.channel_title ?? '(unknown channel)',
    channelId: row.channel_id ?? '',
    publishedAt: row.published_at ?? row.created_at,
    license:
      row.license === 'creativeCommon' || row.license === 'youtube' ? row.license : null,
    endingType: row.ending_type ?? '',
    endingConfidence: row.ending_confidence ?? null,
    nextTopicRemoved: (row.next_topic_removed ?? 0) === 1,
    nextTopicStartSec: row.next_topic_start_sec ?? null,
    nextTopicContamination: row.next_topic_contamination ?? null,
    boundaryStatus: row.boundary_status ?? 'unrefined',
    boundaryConfidence: row.boundary_confidence ?? null,
    startComplete: (row.start_complete ?? 1) === 1,
    endingComplete: row.ending_complete === null ? null : row.ending_complete === 1,
    repairReason: row.repair_reason ?? null,
    roughStartSec: row.rough_start_sec ?? null,
    roughEndSec: row.rough_end_sec ?? null,
    mainTopic: row.main_topic ?? null,
    topicBefore: row.topic_before ?? null,
    topicAfter: row.topic_after ?? null,
    rightsStatus: row.rights_status ?? 'unknown',
    rightsNotes: row.rights_notes ?? null,
    qcStatus: row.qc_status ?? 'pending',
    qcScore: row.qc_score ?? null,
    qcReport: row.qc_report ?? null,
    scheduledAt: row.scheduled_at ?? null,
    targetMarket: row.target_market ?? null,
    idempotencyKey: row.idempotency_key ?? null,
  };
}

const CLIP_SELECT = `
  SELECT
    c.*,
    e.title         AS episode_title,
    e.channel_title AS channel_title,
    e.channel_id    AS channel_id,
    e.published_at  AS published_at,
    e.license       AS license
  FROM clips c
  LEFT JOIN episodes e ON e.video_id = c.video_id
`;

/**
 * Replace the clip set for an episode.
 *
 * Re-analysing an episode (for example after a scoring model change) should
 * produce a clean set rather than duplicates, so the delete and the inserts run
 * in a single transaction.
 */
export function replaceClipsForEpisode(
  videoId: string,
  clips: readonly ScoredClip[],
  runId: number | null,
): void {
  transaction((db) => {
    db.prepare('DELETE FROM clips WHERE video_id = ?').run(videoId);

    const insert = db.prepare(
      `INSERT INTO clips (
        video_id, run_id, segment_index, title, start_sec, end_sec, duration_sec,
        final_score, confidence, tier, category, dimensions, why_this_works,
        suggested_hook, suggested_caption, editing_notes, transcript, engine,
        status, created_at,
        ending_type, ending_confidence, next_topic_removed, next_topic_start_sec, next_topic_contamination,
        boundary_status, boundary_confidence, start_complete, repair_reason,
        rough_start_sec, rough_end_sec, main_topic, topic_before, topic_after,
        rights_status, qc_status, qc_score
      ) VALUES (
        @videoId, @runId, @segmentIndex, @title, @startSec, @endSec, @durationSec,
        @finalScore, @confidence, @tier, @category, @dimensions, @whyThisWorks,
        @suggestedHook, @suggestedCaption, @editingNotes, @transcript, @engine,
        'new', @createdAt,
        @endingType, @endingConfidence, @nextTopicRemoved, @nextTopicStartSec, @nextTopicContamination,
        @boundaryStatus, @boundaryConfidence, @startComplete, @repairReason,
        @roughStartSec, @roughEndSec, @mainTopic, @topicBefore, @topicAfter,
        @rightsStatus, @qcStatus, @qcScore
      )`,
    );

    const createdAt = nowIso();
    for (const clip of clips) {
      insert.run({
        videoId,
        runId,
        segmentIndex: clip.segmentIndex,
        title: clip.title,
        startSec: clip.startSec,
        endSec: clip.endSec,
        durationSec: clip.durationSec,
        finalScore: clip.finalScore,
        confidence: clip.confidence,
        tier: clip.tier,
        category: clip.category,
        dimensions: toJson(clip.dimensions),
        whyThisWorks: toJson(clip.whyThisWorks),
        suggestedHook: clip.suggestedHook,
        suggestedCaption: clip.suggestedCaption,
        editingNotes: clip.editingNotes,
        transcript: clip.transcript,
        engine: clip.engine,
        createdAt,
        endingType: clip.endingType ?? '',
        endingConfidence: clip.endingConfidence ?? null,
        nextTopicRemoved: clip.nextTopicRemoved ? 1 : 0,
        nextTopicStartSec: clip.nextTopicStartSec ?? null,
        nextTopicContamination: clip.nextTopicContamination ?? null,
        boundaryStatus: clip.boundaryStatus ?? 'unrefined',
        boundaryConfidence: clip.boundaryConfidence ?? null,
        startComplete: clip.startComplete === false ? 0 : 1,
        repairReason: clip.repairReason ?? null,
        roughStartSec: clip.roughStartSec ?? null,
        roughEndSec: clip.roughEndSec ?? null,
        mainTopic: clip.mainTopic ?? null,
        topicBefore: clip.topicBefore ?? null,
        topicAfter: clip.topicAfter ?? null,
        rightsStatus: 'unknown',
        qcStatus: 'pending',
        qcScore: null,
      });
    }
  });
}

export type ClipSort = 'score' | 'confidence' | 'recent' | 'duration';

export interface ClipListFilters {
  tiers?: PriorityTier[];
  categories?: ClipCategory[];
  statuses?: ClipStatus[];
  videoId?: string;
  channelId?: string;
  runId?: number;
  /** Filter by reuse rights, e.g. only clips licensed CC BY. */
  licenses?: VideoLicense[];
  minScore?: number;
  minConfidence?: number;
  search?: string;
  /** ISO timestamp; only clips created at or after this instant. */
  createdSince?: string;
  sort?: ClipSort;
  limit?: number;
  offset?: number;
}

const CLIP_SORT_SQL: Record<ClipSort, string> = {
  score: 'c.final_score DESC, c.confidence DESC',
  confidence: 'c.confidence DESC, c.final_score DESC',
  recent: 'c.created_at DESC, c.final_score DESC',
  duration: 'c.duration_sec ASC',
};

function buildClipWhere(filters: ClipListFilters): {
  where: string;
  params: Record<string, unknown>;
} {
  const conditions: string[] = [];
  const params: Record<string, unknown> = {};

  if (filters.tiers && filters.tiers.length > 0) {
    const placeholders = filters.tiers.map((_, index) => `@tier${index}`);
    conditions.push(`c.tier IN (${placeholders.join(', ')})`);
    filters.tiers.forEach((tier, index) => {
      params[`tier${index}`] = tier;
    });
  }

  if (filters.categories && filters.categories.length > 0) {
    const placeholders = filters.categories.map((_, index) => `@category${index}`);
    conditions.push(`c.category IN (${placeholders.join(', ')})`);
    filters.categories.forEach((category, index) => {
      params[`category${index}`] = category;
    });
  }

  if (filters.statuses && filters.statuses.length > 0) {
    const placeholders = filters.statuses.map((_, index) => `@status${index}`);
    conditions.push(`c.status IN (${placeholders.join(', ')})`);
    filters.statuses.forEach((status, index) => {
      params[`status${index}`] = status;
    });
  }

  if (filters.videoId) {
    conditions.push('c.video_id = @videoId');
    params.videoId = filters.videoId;
  }

  if (filters.channelId) {
    conditions.push('e.channel_id = @channelId');
    params.channelId = filters.channelId;
  }

  if (typeof filters.runId === 'number') {
    conditions.push('c.run_id = @runId');
    params.runId = filters.runId;
  }

  if (filters.licenses && filters.licenses.length > 0) {
    const placeholders = filters.licenses.map((_, index) => `@license${index}`);
    conditions.push(`e.license IN (${placeholders.join(', ')})`);
    filters.licenses.forEach((license, index) => {
      params[`license${index}`] = license;
    });
  }

  if (typeof filters.minScore === 'number') {
    conditions.push('c.final_score >= @minScore');
    params.minScore = filters.minScore;
  }

  if (typeof filters.minConfidence === 'number') {
    conditions.push('c.confidence >= @minConfidence');
    params.minConfidence = filters.minConfidence;
  }

  if (filters.createdSince) {
    conditions.push('c.created_at >= @createdSince');
    params.createdSince = filters.createdSince;
  }

  if (filters.search && filters.search.trim().length > 0) {
    conditions.push(
      '(c.title LIKE @search OR c.transcript LIKE @search OR e.title LIKE @search)',
    );
    params.search = `%${filters.search.trim()}%`;
  }

  return {
    where: conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '',
    params,
  };
}

export function listClips(filters: ClipListFilters = {}): ClipRecord[] {
  const { where, params } = buildClipWhere(filters);
  const orderBy = CLIP_SORT_SQL[filters.sort ?? 'score'];

  const rows = getDb()
    .prepare(
      `${CLIP_SELECT} ${where} ORDER BY ${orderBy} LIMIT @limit OFFSET @offset`,
    )
    .all({
      ...params,
      limit: filters.limit ?? 100,
      offset: filters.offset ?? 0,
    }) as ClipRow[];

  return rows.map(mapClip);
}

export function countClips(filters: ClipListFilters = {}): number {
  const { where, params } = buildClipWhere(filters);
  const row = getDb()
    .prepare(
      `SELECT COUNT(*) AS total FROM clips c LEFT JOIN episodes e ON e.video_id = c.video_id ${where}`,
    )
    .get(params) as { total: number };
  return row.total;
}

export function getClip(id: number): ClipRecord | null {
  const row = getDb()
    .prepare(`${CLIP_SELECT} WHERE c.id = ?`)
    .get(id) as ClipRow | undefined;
  return row ? mapClip(row) : null;
}

export function updateClipStatus(id: number, status: ClipStatus): boolean {
  const result = getDb()
    .prepare('UPDATE clips SET status = ? WHERE id = ?')
    .run(status, id);
  return result.changes > 0;
}

/**
 * Persist the render state for a clip. Called by the render integration
 * endpoint before and after the render service runs.
 */
export function updateClipRender(
  id: number,
  params: {
    status: RenderStatus;
    jobId?: string | null;
    path?: string | null;
    error?: string | null;
  },
): boolean {
  const result = getDb()
    .prepare(
      `UPDATE clips
          SET render_status = @status,
              render_job_id = @jobId,
              render_path   = @path,
              render_error  = @error
        WHERE id = @id`,
    )
    .run({
      id,
      status: params.status,
      jobId: params.jobId ?? null,
      path: params.path ?? null,
      error: params.error ?? null,
    });
  return result.changes > 0;
}

/**
 * Persist SEO metadata generated by the LLM for a clip.
 */
export function updateClipSeo(
  id: number,
  params: {
    title: string;
    description: string;
    tags: string[];
  },
): boolean {
  const result = getDb()
    .prepare(
      `UPDATE clips
          SET seo_title        = @title,
              seo_description  = @description,
              seo_tags         = @tags,
              seo_generated_at = @generatedAt
        WHERE id = @id`,
    )
    .run({
      id,
      title: params.title,
      description: params.description,
      tags: toJson(params.tags),
      generatedAt: nowIso(),
    });
  return result.changes > 0;
}

/**
 * Persist publish state for a clip (Phase 3 auto-post integration).
 */
export function updateClipPublish(
  id: number,
  params: {
    status: PublishStatus;
    url?: string | null;
    error?: string | null;
  },
): boolean {
  const result = getDb()
    .prepare(
      `UPDATE clips
          SET publish_status = @status,
              publish_url    = @url,
              publish_error  = @error,
              published_at   = CASE WHEN @status = 'published' THEN @now ELSE published_at END
        WHERE id = @id`,
    )
    .run({
      id,
      status: params.status,
      url: params.url ?? null,
      error: params.error ?? null,
      now: nowIso(),
    });
  return result.changes > 0;
}

/** Phase 3 (Master Task Brief §25): set reuse rights on a clip. */
export function updateClipRights(
  id: number,
  params: {
    status: string;
    notes?: string | null;
  },
): boolean {
  const result = getDb()
    .prepare(
      `UPDATE clips
          SET rights_status = @status,
              rights_notes  = @notes
        WHERE id = @id`,
    )
    .run({
      id,
      status: params.status,
      notes: params.notes ?? null,
    });
  return result.changes > 0;
}

/** Phase 2 (brief §23/§24): persist renderer QC result on a clip. */
export function updateClipQc(
  id: number,
  params: {
    status: string;
    score?: number | null;
    note?: string | null;
  },
): boolean {
  const result = getDb()
    .prepare(
      `UPDATE clips
          SET qc_status = @status,
              qc_score  = @score,
              qc_report = @note
        WHERE id = @id`,
    )
    .run({
      id,
      status: params.status,
      score: params.score ?? null,
      note: params.note ?? null,
    });
  return result.changes > 0;
}

/* -------------------------------------------------------------------------- */
/* PRD "Long-term AI Learning"                                                */
/* -------------------------------------------------------------------------- */

export type FeedbackVerdict = 'agree' | 'disagree' | 'published' | 'rejected';

/**
 * Record an editor's verdict on a clip. This table is the labelled dataset the
 * PRD identifies as the real moat: over time it lets a re-ranker learn what
 * this specific creator's audience responds to, independent of the base LLM.
 */
export function recordClipFeedback(params: {
  clipId: number;
  verdict: FeedbackVerdict;
  note?: string | null;
}): void {
  getDb()
    .prepare(
      `INSERT INTO clip_feedback (clip_id, verdict, note, created_at)
       VALUES (@clipId, @verdict, @note, @createdAt)`,
    )
    .run({
      clipId: params.clipId,
      verdict: params.verdict,
      note: params.note ?? null,
      createdAt: nowIso(),
    });
}

export interface CategoryBreakdown {
  category: ClipCategory;
  count: number;
  averageScore: number;
}

export function clipCategoryBreakdown(filters: ClipListFilters = {}): CategoryBreakdown[] {
  const { where, params } = buildClipWhere(filters);
  const rows = getDb()
    .prepare(
      `SELECT c.category AS category, COUNT(*) AS count, AVG(c.final_score) AS average_score
         FROM clips c
         LEFT JOIN episodes e ON e.video_id = c.video_id
         ${where}
         GROUP BY c.category
         ORDER BY count DESC`,
    )
    .all(params) as { category: string; count: number; average_score: number }[];

  return rows.map((row) => ({
    category: row.category as ClipCategory,
    count: row.count,
    averageScore: Math.round(row.average_score ?? 0),
  }));
}
