/**
 * Golden dataset ingest pipeline (hardening v3 F3) — build.ts.
 *
 * Reads each golden-data/<id>.draft.json + golden-data/<id>.labels.tsv,
 * merges them into a FINAL GoldenFixture JSON, writes it to
 * golden-data/fixtures/<id>.json, and (optionally) regenerates
 * golden-data/index.ts — the runtime loader imports that index so external
 * (real) fixtures join the fixture set without editing source code.
 *
 * Labels TSV format (tab-separated, one labeled window per line):
 *   clipId<TAB>startSec<TAB>endSec<TAB>score<TAB>contamination<TAB>
 *   startComplete<TAB>endingComplete
 *
 * Run:
 *   npx tsx scripts/golden/build.ts <goldenDir> [--topK=3] [--import-index]
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { GoldenFixture } from '../../src/lib/golden/fixtures';

export interface ParsedLabel {
  clipId: string;
  expectedStartSec: number;
  expectedEndSec: number;
  expectedScore: number;
  expectedContamination: number;
  expectedStartComplete: boolean;
  expectedEndingComplete: boolean;
}

export function parseLabel(line: string): ParsedLabel | null {
  const cols = line.split('\t');
  if (cols.length < 7) return null;
  const cleanId = (cols[0] ?? '').trim();
  if (!cleanId || cleanId.startsWith('#') || cleanId === 'clipId') return null;
  // A skeleton row (score or startComplete still empty) is UNREVIEWED — the
  // ingest pipeline writes skeletons for every cue; only rows with a filled
  // score + booleans count as human-approved labels.
  if (!cols[3]?.trim() || !cols[5]?.trim() || !cols[6]?.trim()) return null;
  const s = parseFloat(cols[1] ?? 'NaN');
  const e = parseFloat(cols[2] ?? 'NaN');
  if (!Number.isFinite(s) || !Number.isFinite(e) || e <= s) return null;
  const sc = parseFloat(cols[3] ?? 'NaN');
  const c = parseFloat(cols[4] ?? 'NaN');
  return {
    clipId: cleanId,
    expectedStartSec: s,
    expectedEndSec: e,
    expectedScore: Number.isFinite(sc) ? sc : 0,
    expectedContamination: Number.isFinite(c) ? c : 0,
    expectedStartComplete: String(cols[5] ?? '').trim().toLowerCase() === 'true',
    expectedEndingComplete: String(cols[6] ?? '').trim().toLowerCase() === 'true',
  };
}

export interface BuildOutcome {
  fixtures: GoldenFixture[];
  skipped: string[];
  errors: { id: string; reason: string }[];
}

export function buildFixturesFromDir(goldenDir: string, topK = 3, writeIndex = false): BuildOutcome {
  const out: BuildOutcome = { fixtures: [], skipped: [], errors: [] };
  if (!existsSync(goldenDir)) return out;
  const drafts = readdirSync(goldenDir).filter((f) => f.endsWith('.draft.json'));

  for (const draftFile of drafts) {
    const id = draftFile.replace(/\.draft\.json$/, '');
    try {
      const draft = JSON.parse(readFileSync(join(goldenDir, draftFile), 'utf8'));
      const labels: ParsedLabel[] = [];
      const tsvFile = join(goldenDir, `${id}.labels.tsv`);
      if (existsSync(tsvFile)) {
        for (const raw of readFileSync(tsvFile, 'utf8').split(/\r?\n/)) {
          if (!raw.trim()) continue;
          const lbl = parseLabel(raw);
          if (lbl) labels.push(lbl);
        }
      }
      if (labels.length === 0) {
        out.skipped.push(id);
        continue;
      }
      out.fixtures.push({
        id,
        language: draft?.language,
        captionsQuality: draft?.captionsQuality,
        transcriptCues: (draft?.transcriptCues ?? []).map((c: { startSec: number; endSec: number; text: string }) => ({
          startSec: Number(c.startSec),
          endSec: Number(c.endSec),
          text: String(c.text),
        })),
        labels: labels.map((l) => ({ ...l })),
        topK,
      });
    } catch (e) {
      out.errors.push({ id, reason: e instanceof Error ? e.message : String(e) });
    }
  }

  if (writeIndex && out.fixtures.length > 0) {
    const fxDir = join(goldenDir, 'fixtures');
    mkdirSync(fxDir, { recursive: true });
    for (const fx of out.fixtures) {
      writeFileSync(join(fxDir, `${fx.id}.json`), JSON.stringify(fx, null, 2));
    }
    const varname = (id: string) => 'fx_' + id.replace(/[^a-zA-Z0-9_]/g, '_');
    const imports = out.fixtures
      .map((f) => `import ${varname(f.id)} from "./fixtures/${f.id}.json";`)
      .join('\n');
    const entries = out.fixtures
      .map((f) => `  ${varname(f.id)} as unknown as GoldenFixture,`)
      .join('\n');
    const content =
      '// Generated by scripts/golden/build.ts — do not hand-edit.\n' +
      'import type { GoldenFixture } from "../src/lib/golden/fixtures";\n\n' +
      imports +
      '\n\nexport const EXTERNAL_GOLDEN_FIXTURES: GoldenFixture[] = [\n' +
      entries +
      '\n];\n';
    writeFileSync(join(goldenDir, 'index.ts'), content);
  }
  return out;
}

if (process.argv[1] && process.argv[1] === fileURLToPath(import.meta.url)) {
  const dir = process.argv[2] || 'golden-data';
  const topKArg = process.argv.find((a) => a.startsWith('--topK='));
  const topK = topKArg ? parseInt(topKArg.split('=')[1]!, 10) : 3;
  const writeIndex = process.argv.includes('--import-index');
  const r = buildFixturesFromDir(dir, topK, writeIndex);
  for (const s of r.skipped) console.warn(`skipped ${s}: labels file empty/absent`);
  for (const e of r.errors) console.warn(`err ${e.id}: ${e.reason}`);
  console.log(`built ${r.fixtures.length} fixture(s); skipped ${r.skipped.length}; errors ${r.errors.length}`);
}