// Generated by scripts/golden/build.ts --import-index — do not hand-edit.
// When no external golden fixtures have been annotated yet this file stays
// empty (GOLDEN_FIXTURES = the curated inline set only). Run:
//   npx tsx scripts/golden/build.ts golden-data --import-index
import type { GoldenFixture } from "../src/lib/golden/fixtures";

export const EXTERNAL_GOLDEN_FIXTURES: GoldenFixture[] = [];