import type { ClipCategory } from './categories';
import type { PriorityTier } from './thresholds';

/* -------------------------------------------------------------------------- */
/* Discovery                                                                  */
/* -------------------------------------------------------------------------- */

/** PRD "AI Discovery" - the ways a run can be started. */
export type DiscoveryMode = 'topic' | 'tracked_channels' | 'archive' | 'trending';

export interface ChannelSummary {
  channelId: string;
  title: string;
  handle: string | null;
  thumbnailUrl: string | null;
  subscriberCount: number | null;
  videoCount: number | null;
  viewCount: number | null;
  /** Channel age in days (Phase-2 F10: needed for honest per-day metrics). */
  ageDays?: number | null;
}

/**
 * A YouTube video that looks like a podcast episode, enriched with every
 * signal the Episode Opportunity Score needs.
 */
export interface EpisodeCandidate {
  videoId: string;
  title: string;
  description: string;
  channelId: string;
  channelTitle: string;
  publishedAt: string;
  durationSeconds: number;
  viewCount: number;
  likeCount: number;
  commentCount: number;
  thumbnailUrl: string | null;
  tags: string[];
  /** `null` when the caption track list could not be inspected. */
  hasCaptions: boolean | null;
  /**
   * Reuse rights, straight from the Data API.
   *
   * `creativeCommon` means the owner licensed the video under CC BY, so clips
   * may be reused with attribution. `youtube` is the standard licence and
   * requires the owner's permission. This is the single most useful signal when
   * mining channels you do not own, because it separates the material you can
   * act on from the material that needs a conversation first.
   */
  license: VideoLicense;
  /** False when the owner disabled embedding - a weak signal of reuse posture. */
  embeddable: boolean | null;
  channel: ChannelSummary | null;
}

export type VideoLicense = 'youtube' | 'creativeCommon' | null;

/* -------------------------------------------------------------------------- */
/* Step 2 - Episode Opportunity Score                                         */
/* -------------------------------------------------------------------------- */

export const EPISODE_FACTOR_KEYS = [
  'topicRelevance',
  'durationFit',
  'engagement',
  'viewVelocity',
  'recency',
  'channelQuality',
  'discussionDensity',
  'expectedClipDensity',
  // Phase 2 (Opportunity scoring): channel-relative + economic factors.
  'channelRelativeVelocity',
  'momentum',
  'personalFit',
  'processingCostEfficiency',
] as const;

export type EpisodeFactorKey = (typeof EPISODE_FACTOR_KEYS)[number];

/** Each factor is normalised to 0-100 before weighting. */
export type EpisodeFactorScores = Record<EpisodeFactorKey, number>;

export interface EpisodeOpportunity {
  /** 0-100 weighted composite. */
  score: number;
  factors: EpisodeFactorScores;
  /** Human readable drivers, highest impact first. */
  reasons: string[];
  /** False when the score is below the analysis threshold. */
  eligible: boolean;
  skipReason: string | null;
}

export interface RankedEpisode {
  candidate: EpisodeCandidate;
  opportunity: EpisodeOpportunity;
}

/* -------------------------------------------------------------------------- */
/* Step 3 - Transcript                                                        */
/* -------------------------------------------------------------------------- */

export type TranscriptSource =
  /** Human authored caption track - highest fidelity. */
  | 'youtube_manual'
  /** YouTube automatic speech recognition track. */
  | 'youtube_asr'
  /** Generated by our own speech-to-text fallback. */
  | 'speech_to_text'
  /** Deterministic sample transcript used in demo mode. */
  | 'fixture';

export interface TranscriptCue {
  startSec: number;
  endSec: number;
  text: string;
  /** Phase 4 (brief §34): speaker id when the transcript was diarized. */
  speakerId?: string | null;
  /** Phase 4 (brief §34): role of the speaker. */
  speakerRole?: 'host' | 'guest' | 'unknown' | null;
  /** Phase 4 (brief §34): resolved speaker display name, when known. */
  speakerName?: string | null;
  /**
   * Hardening sprint P0.4: canonical word-level timing, when the transcript
   * vendor provides it (manual captions / high-confidence ASR). Absent means
   * only cue timing is available — the renderer must fall back to forced
   * alignment.
   */
  words?: { startSec: number; endSec: number; text: string }[];
}

export interface Transcript {
  videoId: string;
  source: TranscriptSource;
  language: string;
  cues: TranscriptCue[];
  durationSec: number;
  wordCount: number;
  /** Hardening sprint P0.4: caption provenance. */
  provider?: string;
  transcriptVersion?: string;
  alignmentConfidence?: number;
}

/* -------------------------------------------------------------------------- */
/* Step 4 - Moment detection                                                  */
/* -------------------------------------------------------------------------- */

export interface MomentSegment {
  /** Position of the segment within the episode, 0 based. */
  index: number;
  startSec: number;
  endSec: number;
  durationSec: number;
  text: string;
  wordCount: number;
  wordsPerSecond: number;
  /**
   * 0-1 pre-filter score from cheap lexical heuristics. Used to decide which
   * segments are worth spending an LLM call on.
   */
  salience: number;
  /**
   * Phase-2 correctness (Brief 2 Phase B): stable identity for this candidate
   * across pipeline stages (segment -> clip -> DB) and across re-runs.
   */
  candidateId: string;
  /** Id of the generation run that produced this segment. */
  generationRunId: string;
  /** How many times this candidate's boundary was revised (1 = initial). */
  revision: number;
  /**
   * Hardening sprint Phase C: optional lineage — the candidateId this one was
   * revised from (null for first generation).
   */
  parentCandidateId?: string;
  /** Hardening sprint Phase C: which component set the boundary. */
  boundarySource?: 'rough' | 'semantic' | 'repair' | 'manual';
  /** Hardening sprint Phase C: exact scoring configuration version. */
  scoringVersion?: string;
}

/* -------------------------------------------------------------------------- */
/* Step 5 - Clip scoring                                                      */
/* -------------------------------------------------------------------------- */

export const CLIP_DIMENSION_KEYS = [
  'hook',
  'curiosity',
  'emotion',
  'storytelling',
  'standalone',
  'shareability',
  'clarity',
  'controversy',
  'teachingValue',
  'entertainment',
] as const;

export type ClipDimensionKey = (typeof CLIP_DIMENSION_KEYS)[number];

/** Every dimension is 0-100. */
export type ClipDimensionScores = Record<ClipDimensionKey, number>;

export type ScoringEngineName = 'llm' | 'heuristic';

/** Raw judgement returned by a scoring engine, before post-processing. */
export interface ClipJudgement {
  dimensions: ClipDimensionScores;
  title: string;
  category: ClipCategory;
  /** PRD Step 10 - short tags such as "Strong Hook", "High Emotion". */
  whyThisWorks: string[];
  suggestedHook: string;
  suggestedCaption: string;
  editingNotes: string;
  engine: ScoringEngineName;
  /** Engine-reported self-certainty, 0-1. Feeds the confidence model. */
  selfCertainty: number;
}

/** PRD Step 8 - the full metadata payload for one clip. */
export interface ScoredClip {
  segmentIndex: number;
  startSec: number;
  endSec: number;
  durationSec: number;
  title: string;
  transcript: string;
  dimensions: ClipDimensionScores;
  finalScore: number;
  /** 0-100, rendered as a percentage in the UI. */
  confidence: number;
  tier: PriorityTier;
  category: ClipCategory;
  whyThisWorks: string[];
  suggestedHook: string;
  suggestedCaption: string;
  editingNotes: string;
  engine: ScoringEngineName;
  /** Phase 1 (Correctness): highlight debug report fields (brief §52). */
  endingType?: string;
  endingConfidence?: number | null;
  nextTopicRemoved?: boolean;
  nextTopicStartSec?: number | null;
  nextTopicContamination?: number | null;
  /** Phase 1 (Master Task Brief §12-14): boundary workflow + debug report. */
  boundaryStatus?: string;
  boundaryConfidence?: number | null;
  startComplete?: boolean;
  repairReason?: string | null;
  roughStartSec?: number | null;
  roughEndSec?: number | null;
  /** Brief 2 Phase B: stable identity propagated from the segment. */
    candidateId?: string;
    generationRunId?: string;
    revision?: number;
    /** Hardening Phase C: lineage + source + scoring version. */
    parentCandidateId?: string;
    boundarySource?: string;
    scoringVersion?: string;
  mainTopic?: string | null;
  topicBefore?: string | null;
  topicAfter?: string | null;
}

/* -------------------------------------------------------------------------- */
/* Pipeline                                                                   */
/* -------------------------------------------------------------------------- */

export interface RunRequest {
  mode: DiscoveryMode;
  /** Required for `topic` mode. */
  topic?: string;
  /** Required for `tracked_channels` and `archive` mode. */
  channelIds?: string[];
  /** Maximum number of episodes to pull from discovery. */
  maxEpisodes?: number;
  /** Episode Opportunity Score gate. Episodes below this are never analysed. */
  episodeScoreThreshold?: number;
  /** Only persist clips at or above this final score. */
  clipScoreThreshold?: number;
  /** Only consider episodes published within this many days. */
  publishedWithinDays?: number;
}

export interface EpisodeAnalysisResult {
  episode: EpisodeCandidate;
  opportunity: EpisodeOpportunity;
  analysed: boolean;
  skipReason: string | null;
  transcriptSource: TranscriptSource | null;
  segmentCount: number;
  clips: ScoredClip[];
}

export interface AiUsageSummary {
  calls: number;
  inputTokens: number;
  outputTokens: number;
}

export interface RunSummary {
  runId: number;
  mode: DiscoveryMode;
  topic: string | null;
  startedAt: string;
  finishedAt: string;
  durationMs: number;
  engine: ScoringEngineName;
  /** Whether discovery hit the live API or the demo catalogue. */
  discoverySource: 'live' | 'demo';
  /** The queries discovery actually ran, after agent expansion. */
  searchQueries: string[];
  episodesDiscovered: number;
  episodesAnalysed: number;
  episodesSkipped: number;
  clipsFound: number;
  tierCounts: Record<PriorityTier, number>;
  aiUsage: AiUsageSummary;
  warnings: string[];
  results: EpisodeAnalysisResult[];
}

/* -------------------------------------------------------------------------- */
/* Dashboard                                                                  */
/* -------------------------------------------------------------------------- */

export interface DashboardStats {
  podcastsDiscovered: number;
  episodesAnalysed: number;
  potentialClips: number;
  highPriority: number;
  publishImmediately: number;
}
